// Copies app/legal-static/{terms,privacy}/index.html (generated by
// `npm run legal:export` in server/, from server/src/routes/legal.ts) into the
// Expo web build output so Vercel serves /legal/terms and /legal/privacy at a
// permanent URL — needed for Facebook App Review, which requires stable
// Terms/Privacy links and this server isn't deployed anywhere persistent.
import { cp, access } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.resolve(here, "../legal-static");
const dest = path.resolve(here, "../dist/legal");

try {
  await access(src);
} catch {
  console.warn(`[copyLegalStatic] ${src} not found — run "npm run legal:export" in server/ first. Skipping.`);
  process.exit(0);
}

await cp(src, dest, { recursive: true });
console.log(`[copyLegalStatic] copied ${src} -> ${dest}`);
